// DO NOT EDIT. This file is generated by fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import config from "./deno.json" assert { type: "json" };
import * as $0 from "./routes/_middleware.ts";
import * as $1 from "./routes/admin/index.tsx";
import * as $2 from "./routes/admin/profile.tsx";
import * as $3 from "./routes/auth/callback.tsx";
import * as $4 from "./routes/auth/logout.ts";
import * as $5 from "./routes/index.tsx";

const manifest = {
  routes: {
    "./routes/_middleware.ts": $0,
    "./routes/admin/index.tsx": $1,
    "./routes/admin/profile.tsx": $2,
    "./routes/auth/callback.tsx": $3,
    "./routes/auth/logout.ts": $4,
    "./routes/index.tsx": $5,
  },
  islands: {},
  baseUrl: import.meta.url,
  config,
};

export default manifest;
